export const types = {
    ADD_CART: "ADD_CART",
    UPDATE_UP_QTY_CART: "UPDATE_UP_QTY_CART",
    UPDATE_DOWN_QTY_CART: "UPDATE_DOWN_QTY_CART",
    UPDATE_INPUT_QTY_CART: "UPDATE_INPUT_QTY_CART",
    DELETE_CART: "DELETE_CART"
}

